### ISSUE TITLE
Rule E restriction can't be lifted if OP deleted their post

### ISSUE THREAD

**Issue by Snorrrlax** [perezdev/CMVModBot#22]
An OP keeps getting their new post removed because of this Rule E break: https://www.reddit.com/r/changemyview/comments/82af78/cmv_frank_underwood_should_stop_talking_to/

Despite deleting the post, they replied to the comments in order to get the restriction lifted. However, the bot isn't recognising this, presumably because the 'OP' title doesn't exist after deletion. I had to manually remove the Rule E SnooNote to let it through. 

Can the bot search for username instead?

**Comment by perezdev** [comment]
This is perplexing. I looked through the code line by line and everything looks okay. The bot pulls the post URL from SnooNotes and crawls through the post to see if OP responded. Deleted or not, if it didn't find the post, it would've crashed because the bot always assume it can reach the post. And if it crashed, it wouldn't have remove OP's posts. I think we're going to have to close this for now and revisit it once it happens again.

**Comment by Snorrrlax** [comment]
Once a post is deleted, I think the OP identifier disappears. So OP's comments within the thread look like everyone else's comments. Is that the reason? In which case, the bot will need to take the username into consideration.

**Comment by perezdev** [comment]
The bot already does that. It pulls the comments and checks the user name of each comment.
